{% set name = "aws-s3-cli" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0d40ed30d285bd0a1709ded86306f7ece329755f441d76f3c5a7d8f9aca698d2

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - boto3
    - python >={{ python_min }}

test:
  imports:
    - aws_s3_cli
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sujitmandal/aws-s3-cli
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: upload, download, check file availability, and get all available list from AWS s3 bucket.
  doc_url: https://sujitmandal.github.io/aws-s3-cli/
  dev_url: https://github.com/sujitmandal/aws-s3-cli/

extra:
  recipe-maintainers:
    - sujitmandal
